homepage = "indexes/posts/docs-1.html"
longdate = "Jan 2, 2006"
#urlprefix = "https://blog.example.com"

# Exclude Vim backup and temp files.
exclude = "*~|4913"

# Uncomment the id line to enable default document ids for published documents.
# If you want to confine default ids to blog posts put it in `template/posts/config.toml`.
#id = "urlpath"


[user]
# Header text at the top of each page.
banner = "hindsite | blog"

# Default HTML title element text.
title = "hindsite blog"

# Set shortname to your site's Disqus short name then uncomment the line to enable Disqus comments.
# See https://help.disqus.com/installation/whats-a-shortname
#shortname = "disqus-shortname-goes-here"

# Include highlight.js support.
#highlightjs = "yes";
